name: Secret Scanning Disabled
on:
  # Intentionally disabled
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Log message
        run: echo "Secret scanning is currently disabled" 